#eval

In [80]:
eval('4+6')

10

In [81]:
eval("3+6j")

(3+6j)

In [82]:
abs(3+6j)

6.708203932499369

#task

user will be given a question:
give an answer
evaluate and tell the user

In [ ]:
"5*7"   #1,10
35

#random

In [84]:
import random as r

In [91]:
r.seed(2)
r.random()

0.9560342718892494

In [92]:
r.randint(1,45)

4

In [97]:
r.sample(range(100),3)

[55, 81, 50]

In [100]:
colors=["r","b","g"]
r.choice(colors)

'b'

In [106]:
r.choices(colors,k=10,weights=[0.6,0.8,0])

['b', 'b', 'r', 'r', 'r', 'r', 'b', 'b', 'b', 'r']

# Iterators

In [11]:
l=[1,2,3]
dir(l)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [13]:
#__iter__(), __next__()
x=iter(l)    #lazy evaluation

In [14]:
next(x)

1

In [15]:
next(x)

2

In [18]:
next(x)

StopIteration: 

In [21]:
#
class DummyIterator:
    def __iter__(self):
        self.start=1
        return self
    
    def __next__(self):
        n=self.start
        self.start+=1
        return n
    
ob=DummyIterator()
x=iter(ob)


In [34]:
next(x)


9

# Generators

In [26]:
def square(num):
    for i in range(num):
        yield i**2

In [37]:
x=square(4)


In [40]:
next(x)

4

In [50]:
def data(max_value):
    initial=1
    while initial<=max_value:
        yield initial
        initial+=1
        
ob=data(10**8)        

In [51]:
import sys

In [53]:
sys.getsizeof(ob)

104

In [56]:
d=list(data(10**8))

In [57]:
sys.getsizeof(d)

835128600

# Decorators

In [ ]:
#function return another function
#can you pass a function to a variable
#nested function
#function as argument to another function

In [65]:
def decorate_msg(func):
    def inner():
        f=func()
        converted=f.upper()
        return converted
    return inner

@decorate_msg
def msg():
    return "Neend toh nahi aa rahi?"

In [66]:
msg()

'NEEND TOH NAHI AA RAHI?'

In [74]:
def decorate_divide(func):
    def inner(a,b):
        print(f'{a} will be divided by {b}')
        if b==0:
            print("cannot divide")
            return 
        return func(a,b)
    return inner

In [77]:
@decorate_divide
def divide(a,b):
    return a/b

In [79]:
divide(3,8)

3 will be divided by 8


0.375

# Numpy

In [ ]:
#array creation routines

In [112]:
import numpy as np
arr2 = np.array([[1,2,3], [4,5,6],[7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [113]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [114]:
arr3 = np.array([[[1,2,3], [4,5,6],[7, 8, 9]],[[1,2,3], [4,5,6],[7, 8, 9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [119]:
arr3.itemsize*18

72

In [120]:
sys.getsizeof(arr3)

216

In [121]:
sys.getsizeof(arr2)

164

In [122]:
arr2.itemsize*9

36

In [124]:
np.full((10,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [127]:
data=np.linspace(1,2,10).reshape(5,2)

In [131]:
data.reshape(-1,1).shape

(10, 1)

In [132]:
#aggregation function
data.sum()

15.0

In [ ]:
#joining and splitting

In [ ]:
#concatenate, axis=0,1
#stack
#vstack
#hstack
#column_stack

In [ ]:
#split
#vsplit
#hsplit

In [ ]:
#reshaping



In [135]:
translate_str=str.maketrans("pqr","xyz")
"pqrxyzABC".translate(translate_str)

'xyzxyzABC'

#Assessment: Numpy Case Study


**Problem Statement:** 

A movie review website needs to create a database to store their data and perform operations on it. Create a dummy model with 100 users and 1000 movies to explain how it will work.

**Topics Covered:**
- NumPy
    - numpy.ndarray
    - Statistical operations using NumPy
    - Mathematical operations using NumPy
    
**Tasks to be performed:**
1. Generate 1000 movie IDs starting from 1301
2. Create a matrix movies_matrix, to store users rating such that
    - There are 100 users
    - Each user can review as many movies as they want
    - The review should be in between 0 to 10 (both inclusive)
3. We have ten movie experts, let us take their reviews as well. 50 new movies and their reviews have to be added 
4. Create final_movie_rating matrix with four columns i.e., 'Movie ID', 'Average rating', 'Number of ratings', and           'Standard deviation of ratings'


Bonus Questions

5. Display the movies rating-wise, highest to lowest

6. Store the array in a file and save it (file handling in Numpy)

In [ ]:
#100*1000
1. 8,7,-1,5,6,-1,0
2. 