In [1]:
#Day 2 Numpy Case Study

In [29]:
import pandas as pd
import numpy as np
import random

movie_id=np.arange(1301,2301)
movie_id

array([1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311,
       1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322,
       1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333,
       1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344,
       1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355,
       1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366,
       1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377,
       1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388,
       1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399,
       1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410,
       1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421,
       1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432,
       1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443,
       1444, 1445, 1446, 1447, 1448, 1449, 1450, 14

In [30]:
arr=np.full(1000,-1)
arr

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [31]:
movies_to_rate=random.randint(0,1000)
movies_to_rate  #Randomly selecting movies to be rated

179

In [32]:
places=random.sample(range(0,999),movies_to_rate)
places

[106,
 95,
 972,
 874,
 64,
 181,
 279,
 378,
 55,
 134,
 966,
 598,
 865,
 689,
 902,
 762,
 139,
 336,
 820,
 409,
 986,
 335,
 404,
 358,
 804,
 886,
 453,
 529,
 56,
 28,
 311,
 16,
 454,
 217,
 839,
 114,
 23,
 329,
 905,
 927,
 478,
 538,
 493,
 527,
 419,
 574,
 817,
 72,
 871,
 507,
 585,
 254,
 153,
 413,
 883,
 83,
 417,
 923,
 674,
 496,
 530,
 265,
 858,
 322,
 807,
 915,
 29,
 400,
 757,
 884,
 138,
 148,
 184,
 516,
 81,
 854,
 14,
 509,
 76,
 455,
 49,
 289,
 230,
 668,
 845,
 997,
 437,
 222,
 174,
 730,
 421,
 47,
 722,
 234,
 150,
 909,
 803,
 934,
 594,
 832,
 601,
 73,
 523,
 324,
 348,
 774,
 66,
 747,
 546,
 834,
 811,
 6,
 719,
 654,
 789,
 950,
 537,
 340,
 683,
 917,
 398,
 346,
 3,
 35,
 956,
 10,
 885,
 109,
 433,
 535,
 19,
 665,
 579,
 618,
 660,
 132,
 62,
 125,
 140,
 873,
 472,
 79,
 977,
 693,
 815,
 135,
 712,
 367,
 103,
 626,
 260,
 512,
 244,
 776,
 397,
 791,
 505,
 534,
 611,
 655,
 314,
 13,
 818,
 687,
 862,
 554,
 456,
 331,
 942,
 256,
 671,
 

In [33]:
for i in arr:
  for index in places:
     arr[index] = random.randint(0,10)

In [34]:
arr

array([-1, -1, -1,  4, -1, -1,  7, -1, -1, -1,  2, -1, -1,  8, 10, -1,  9,
       -1, -1,  2, -1, -1, -1,  8, -1, -1, -1, -1,  0,  8, -1, -1, -1, -1,
       -1,  5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  6, -1,  2, -1,
       -1, -1, -1, -1,  5,  8, -1, -1, -1, -1, -1,  5, -1,  9, -1,  2, -1,
       -1, -1, -1, -1, 10, 10, -1, -1,  9, -1, -1,  6, -1,  2, -1,  0, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  8, -1, -1, -1, -1, -1, -1,
       -1,  1, -1, -1, 10, -1, -1,  6, -1, -1, -1, -1,  0, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  4, -1, -1, -1, -1, -1, -1,  4, -1,  3,  8,
       -1, -1,  1,  1,  9, -1, -1, -1, -1, -1, -1, -1,  3, -1,  4, -1, -1,
        3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  4, -1, -1, -1, -1, -1, -1,  3, -1, -1,  0, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, -1, -1, -1,
       -1,  3, -1, -1, -1

In [35]:
users=100
movies=1000
movie_matrix=np.random.randint(-1,11,size=(users,movies))
movie_matrix

array([[ 2,  3,  8, ..., -1, 10, 10],
       [ 5, 10,  3, ...,  3,  3,  7],
       [ 1,  4,  8, ...,  7,  6,  0],
       ...,
       [ 7,  8,  5, ...,  0,  0,  8],
       [ 6, -1,  9, ...,  2, 10,  5],
       [ 3, 10,  3, ...,  5,  6,  3]])

In [36]:
df=pd.DataFrame(movie_matrix,columns=movie_id)
df

1301  1302  1303  1304  1305  1306  1307  1308  1309  1310  ...  2291  \
0      2     3     8     9     0     1     2     9     3     0  ...    10   
1      5    10     3     7     7     5     2    10     1     1  ...     6   
2      1     4     8     8    10     6    -1     5    -1     1  ...     4   
3      7     5     3     7    10    -1     4     2     9     8  ...     8   
4      1     6     9     2     3     2    10     8     3     8  ...     9   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
95     3    -1     4     9     8     7     9     8     4     0  ...     0   
96     8     2     6     5     6     6     8     5     8     8  ...    -1   
97     7     8     5     5     1     2     2     9    10     0  ...     5   
98     6    -1     9     7    10    -1     4     5     4     6  ...     4   
99     3    10     3     7     5     3     3    -1     2     9  ...     6   

    2292  2293  2294  2295  2296  2297  2298  2299  2300  
0      0     2     4    -1    10     1    -1    10    10  
1      6     3     2     5     6     6     3     3     7  
2      0    -1     7     5     5     6     7     6     0  
3      2     1     2    10    -1     0    -1     8     9  
4      8     0     1     9     6     7     4     1     5  
..   ...   ...   ...   ...   ...   ...   ...   ...   ...  
95     6     1     3     5     7     8     6     5     5  
96     0     5     3     3     3    -1     1    10     1  
97     9     9     8     1     4     7     0     0     8  
98     3    10     3     7    -1     9     2    10     5  
99     3     7     5     6    -1     6     5     6     3  

[100 rows x 1000 columns]

In [46]:
# Appended users=10 movies=50
new_movie_id=np.arange(2301,2351)

1301  1302  1303  1304  1305  1306  1307  1308  1309  1310  ...  2341  \
0      2     3     8     9     0     1     2     9     3     0  ...    -1   
1      5    10     3     7     7     5     2    10     1     1  ...    -1   
2      1     4     8     8    10     6    -1     5    -1     1  ...    -1   
3      7     5     3     7    10    -1     4     2     9     8  ...    -1   
4      1     6     9     2     3     2    10     8     3     8  ...    -1   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
95     3    -1     4     9     8     7     9     8     4     0  ...    -1   
96     8     2     6     5     6     6     8     5     8     8  ...    -1   
97     7     8     5     5     1     2     2     9    10     0  ...    -1   
98     6    -1     9     7    10    -1     4     5     4     6  ...    -1   
99     3    10     3     7     5     3     3    -1     2     9  ...    -1   

    2342  2343  2344  2345  2346  2347  2348  2349  2350  
0      7     3     8     1     5     6     6     1     2  
1      7     3     8     1     5     6     6     1     2  
2      7     3     8     1     5     6     6     1     2  
3      7     3     8     1     5     6     6     1     2  
4      7     3     8     1     5     6     6     1     2  
..   ...   ...   ...   ...   ...   ...   ...   ...   ...  
95     7     3     8     1     5     6     6     1     2  
96     7     3     8     1     5     6     6     1     2  
97     7     3     8     1     5     6     6     1     2  
98     7     3     8     1     5     6     6     1     2  
99     7     3     8     1     5     6     6     1     2  

[100 rows x 1050 columns]

In [49]:
new_movie_user=np.arange(101,111)
#new_movie_user
df

1301  1302  1303  1304  1305  1306  1307  1308  1309  1310  ...  2341  \
0      2     3     8     9     0     1     2     9     3     0  ...    -1   
1      5    10     3     7     7     5     2    10     1     1  ...    -1   
2      1     4     8     8    10     6    -1     5    -1     1  ...    -1   
3      7     5     3     7    10    -1     4     2     9     8  ...    -1   
4      1     6     9     2     3     2    10     8     3     8  ...    -1   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
95     3    -1     4     9     8     7     9     8     4     0  ...    -1   
96     8     2     6     5     6     6     8     5     8     8  ...    -1   
97     7     8     5     5     1     2     2     9    10     0  ...    -1   
98     6    -1     9     7    10    -1     4     5     4     6  ...    -1   
99     3    10     3     7     5     3     3    -1     2     9  ...    -1   

    2342  2343  2344  2345  2346  2347  2348  2349  2350  
0      7     3     8     1     5     6     6     1     2  
1      7     3     8     1     5     6     6     1     2  
2      7     3     8     1     5     6     6     1     2  
3      7     3     8     1     5     6     6     1     2  
4      7     3     8     1     5     6     6     1     2  
..   ...   ...   ...   ...   ...   ...   ...   ...   ...  
95     7     3     8     1     5     6     6     1     2  
96     7     3     8     1     5     6     6     1     2  
97     7     3     8     1     5     6     6     1     2  
98     7     3     8     1     5     6     6     1     2  
99     7     3     8     1     5     6     6     1     2  

[100 rows x 1050 columns]

In [39]:
new_movie_matrix=np.random.randint(0,11,size=(10,50))
new_movie_matrix

array([[ 3,  7,  1,  0,  0,  2,  1,  1,  1,  1,  5,  4,  2,  3,  2,  1,
         2,  2, 10,  9,  1,  2,  3,  1,  8,  3,  2,  4,  7,  8,  7,  0,
         8,  4,  4,  8, 10,  3,  8,  0,  1,  2,  0, 10,  5,  7,  3,  4,
         1,  1],
       [10,  4,  5, 10,  5, 10,  0,  3,  8,  7,  3,  4,  6,  1,  8,  0,
         3,  8,  5,  7,  8, 10,  4, 10,  3,  4,  3,  9,  9,  7,  2,  4,
         6,  1,  5,  2,  4,  9,  7,  8,  6,  7,  2,  3,  5,  3,  6,  8,
         9,  9],
       [ 5,  5,  1,  0,  1,  2,  5,  8,  4,  8, 10,  7,  9,  8,  1,  6,
        10,  4,  8,  5,  4,  6,  5,  9,  8,  6,  7,  6,  6,  0,  3,  7,
         9,  8, 10,  2,  6,  5,  5,  3,  6,  9,  2, 10,  1,  2,  6,  2,
         3,  7],
       [ 8,  1,  5,  9,  9,  4,  9,  9,  1,  4, 10,  0,  2,  1,  4,  8,
         9,  9,  1,  3, 10,  7,  0,  5,  6,  4,  9,  5,  2,  9,  9, 10,
         1,  0,  1,  4,  1,  3,  5,  2,  0,  0,  4,  3,  4,  8,  0,  7,
         5,  5],
       [ 0,  8,  1,  8,  2,  2,  6, 10,  9,  0,  9, 10,  6,  0,  8, 

In [50]:
for i in range(50):
    df[new_movie_id[i]] = np.random.randint(-1,11,size=(100,1050))  # Merging new movie id with rating =-1 in old dataframe

In [57]:
new_movie_matrix.shape

(10, 50)

In [51]:
df

1301  1302  1303  1304  1305  1306  1307  1308  1309  1310  ...  2341  \
0      2     3     8     9     0     1     2     9     3     0  ...     7   
1      5    10     3     7     7     5     2    10     1     1  ...     1   
2      1     4     8     8    10     6    -1     5    -1     1  ...     8   
3      7     5     3     7    10    -1     4     2     9     8  ...     7   
4      1     6     9     2     3     2    10     8     3     8  ...     2   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
95     3    -1     4     9     8     7     9     8     4     0  ...     2   
96     8     2     6     5     6     6     8     5     8     8  ...     1   
97     7     8     5     5     1     2     2     9    10     0  ...     3   
98     6    -1     9     7    10    -1     4     5     4     6  ...    10   
99     3    10     3     7     5     3     3    -1     2     9  ...     6   

    2342  2343  2344  2345  2346  2347  2348  2349  2350  
0      4     8    -1    -1     2     8     0    -1     1  
1      0    -1     5    10    10     0     2     4    10  
2      5    -1     4     2     3     3     8     1     4  
3      7     2     9     7     4     3     1     9     3  
4     -1     7     0     3     2     0     7    -1     7  
..   ...   ...   ...   ...   ...   ...   ...   ...   ...  
95     3     7     4     0     0     8     6     0     9  
96     2     5     4     2     6    10     1     2     8  
97     8     2     7     3     0     1    10    -1     9  
98     5     5     3     4     5     7    10     1    -1  
99     9     2     6     7     3     9     4     6    10  

[100 rows x 1050 columns]

In [52]:
for i in range(10):
    expert_ratings = new_movie_matrix[i]
    random_movie_indexes = np.random.choice(range(50), size=10, replace=False)

    for j in range(10):
        df.at[random_movie_indexes[j], new_movie_id[i]] = expert_ratings[j]
        
df

1301  1302  1303  1304  1305  1306  1307  1308  1309  1310  ...  2341  \
0      2     3     8     9     0     1     2     9     3     0  ...     7   
1      5    10     3     7     7     5     2    10     1     1  ...     1   
2      1     4     8     8    10     6    -1     5    -1     1  ...     8   
3      7     5     3     7    10    -1     4     2     9     8  ...     7   
4      1     6     9     2     3     2    10     8     3     8  ...     2   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
95     3    -1     4     9     8     7     9     8     4     0  ...     2   
96     8     2     6     5     6     6     8     5     8     8  ...     1   
97     7     8     5     5     1     2     2     9    10     0  ...     3   
98     6    -1     9     7    10    -1     4     5     4     6  ...    10   
99     3    10     3     7     5     3     3    -1     2     9  ...     6   

    2342  2343  2344  2345  2346  2347  2348  2349  2350  
0      4     8    -1    -1     2     8     0    -1     1  
1      0    -1     5    10    10     0     2     4    10  
2      5    -1     4     2     3     3     8     1     4  
3      7     2     9     7     4     3     1     9     3  
4     -1     7     0     3     2     0     7    -1     7  
..   ...   ...   ...   ...   ...   ...   ...   ...   ...  
95     3     7     4     0     0     8     6     0     9  
96     2     5     4     2     6    10     1     2     8  
97     8     2     7     3     0     1    10    -1     9  
98     5     5     3     4     5     7    10     1    -1  
99     9     2     6     7     3     9     4     6    10  

[100 rows x 1050 columns]

In [53]:
#final movie matrix with four col.
final_movie_rating=pd.DataFrame(df,columns=['Movie ID', 'Average rating', 'Number of ratings', 'Standard deviation of ratings'])
final_movie_rating

Movie ID  Average rating  Number of ratings  Standard deviation of ratings
0        NaN             NaN                NaN                            NaN
1        NaN             NaN                NaN                            NaN
2        NaN             NaN                NaN                            NaN
3        NaN             NaN                NaN                            NaN
4        NaN             NaN                NaN                            NaN
..       ...             ...                ...                            ...
95       NaN             NaN                NaN                            NaN
96       NaN             NaN                NaN                            NaN
97       NaN             NaN                NaN                            NaN
98       NaN             NaN                NaN                            NaN
99       NaN             NaN                NaN                            NaN

[100 rows x 4 columns]

In [54]:
df.columns

Index([1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310,
       ...
       2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350],
      dtype='int32', length=1050)

In [55]:
final_movie_rating['Movie ID']=df.columns

ValueError: Length of values (1050) does not match length of index (100)

In [17]:
for movie_id in df.columns:
    if movie_id not in final_movie_rating['Movie ID'].values:
        ratings = random.randint(0,1000)
        avg_rating = np.mean(ratings)
        num_ratings = random.randint(0,1000)
        std_dev = np.std(ratings)
        final_movie_rating = final_movie_rating.append({'Movie ID': movie_id,
                                                            'Average rating': avg_rating,
                                                            'Number of ratings': num_ratings,
                                                            'Standard deviation of ratings': std_dev},
                                                           ignore_index=True)

# Display the final_movie_rating matrix
final_movie_rating.head(10)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
final_movie_rating.shape